# SPDX-License-Identifier: MIT
# Copyright 2026 Tyler Zervas

version: 2
updates:
  # Maintain Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      candle:
        patterns:
          - "candle*"
      cubecl:
        patterns:
          - "cubecl*"
    labels:
      - "dependencies"
      - "rust"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
